### ISSUE TITLE
[CI] cancel in progress builds when a new push occurs

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/checkpoint#384]
Make sure that older builds get canceled when new changes are pushed to a PR:
```yml
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
```
https://github.com/DARMA-tasking/workflows/pull/17#discussion_r1991654185

---
Also: use that issue to get rid of the dead links on the front page.
![Image](https://github.com/user-attachments/assets/6b388c2f-e706-4bf9-9cbe-e56a6cd28efc)
